version: "3.8"
services:

  db:
    image: postgres:14.1
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata

    environment:

      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project-db
    
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4

    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - 5050:80

volumes:
  app-db-data:
